version: '3.8'

services:
  gatsby:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules # biar node_modules gak rusak di host
    environment:
      - NODE_ENV=development